#!/usr/bin/env python3
"""
Generate complete metadata for all datasets using pre-generated content.
This script creates the metadata that would be generated by Claude API.
"""

import yaml
from pathlib import Path
from typing import Dict, Any, List

# Pre-generated metadata for datasets
# In production, these would come from Claude Haiku API
METADATA_LIBRARY = {
    "l3cube-mahasent-md": {
        "schema": [
            {"field": "text", "type": "string", "description": "The Marathi text sample"},
            {"field": "sentiment", "type": "string", "description": "Sentiment label (positive, negative, neutral)"},
            {"field": "domain", "type": "string", "description": "Domain of the text (news, social, reviews, etc.)"},
            {"field": "language", "type": "string", "description": "Language code (mr for Marathi)"}
        ],
        "starter_idea": "Build a Marathi sentiment analysis service to monitor social media conversations about government policies",
        "build_ideas": [
            "Create a Marathi sentiment classifier for customer review analysis on e-commerce platforms",
            "Develop a real-time sentiment dashboard for tracking public opinion on agricultural policies",
            "Build a multilingual sentiment API that handles Marathi, Hindi, and English for startup feedback analysis"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/mahasent')\nfor ex in ds['train'].take(5):\n    print(f\"{ex['text']}: {ex['sentiment']}\")"
    },

    "l3cube-mahaner": {
        "schema": [
            {"field": "tokens", "type": "list[string]", "description": "List of tokens/words"},
            {"field": "ner_tags", "type": "list[int]", "description": "BIO entity tags (0=O, 1=B-PER, etc.)"},
            {"field": "id", "type": "string", "description": "Unique identifier for the sentence"},
            {"field": "sentence", "type": "string", "description": "Original Marathi sentence"}
        ],
        "starter_idea": "Build a named entity recognition service to extract person, organization, and location names from Marathi government documents",
        "build_ideas": [
            "Create a knowledge graph from Marathi news articles using this NER dataset",
            "Develop a Marathi legal document parser that extracts entities for contract analysis",
            "Build a fine-tuned NER model for identifying crop names and agricultural organizations in Marathi advisory texts"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/marathi-ner')\nexample = ds['train'][0]\nprint(f\"Tokens: {example['tokens']}\")\nprint(f\"Tags: {example['ner_tags']}\")"
    },

    "l3cube-mahahate": {
        "schema": [
            {"field": "text", "type": "string", "description": "Marathi text sample"},
            {"field": "is_hate", "type": "boolean", "description": "Whether text contains hate speech"},
            {"field": "category", "type": "string", "description": "Type of hate (religious, caste, gender, etc.)"},
            {"field": "source", "type": "string", "description": "Source of the text (social media, comments, etc.)"}
        ],
        "starter_idea": "Build a content moderation service to automatically flag hate speech in Marathi social media platforms",
        "build_ideas": [
            "Create a real-time hate speech detector for Marathi community forum platforms",
            "Develop a caste-abuse detection system specific to Indian social contexts",
            "Build an alert system for monitoring Marathi-language hate speech trends for civil society organizations"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/marathi-hate')\nhate_examples = [ex for ex in ds['train'] if ex['is_hate']]\nprint(f\"Hate speech samples: {len(hate_examples)}\")\nfor ex in hate_examples[:3]:\n    print(f\"  - {ex['text']}\")"
    },

    "l3cube-mahaparaphrase": {
        "schema": [
            {"field": "text_a", "type": "string", "description": "First Marathi sentence"},
            {"field": "text_b", "type": "string", "description": "Second Marathi sentence (paraphrase)"},
            {"field": "is_paraphrase", "type": "boolean", "description": "Whether the sentences are paraphrases"},
            {"field": "score", "type": "float", "description": "Similarity score (0-1)"}
        ],
        "starter_idea": "Build a semantic search engine for Marathi educational content that finds similar questions and answers",
        "build_ideas": [
            "Create a question deduplication system for Marathi Q&A platforms using paraphrase detection",
            "Develop a FAQ matching system that identifies if a new question is already answered",
            "Build a content recommendation system that suggests related Marathi articles based on semantic similarity"
        ],
        "quick_start": "from datasets import load_dataset\nfrom sentence_transformers import util\nds = load_dataset('l3cube-pune/marathi-paraphrase')\nfor ex in ds['train'].take(3):\n    print(f\"A: {ex['text_a']}\")\n    print(f\"B: {ex['text_b']}\")\n    print(f\"Match: {ex['is_paraphrase']}\\n\")"
    },

    "l3cube-mahasquad": {
        "schema": [
            {"field": "question", "type": "string", "description": "Question in Marathi"},
            {"field": "context", "type": "string", "description": "Context paragraph containing the answer"},
            {"field": "answer_text", "type": "string", "description": "Text of the answer"},
            {"field": "answer_start", "type": "int", "description": "Starting character position of answer in context"}
        ],
        "starter_idea": "Build a Marathi question-answering system for agricultural advisory queries from farmers",
        "build_ideas": [
            "Create a RAG system for answering questions from Marathi Wikipedia content",
            "Develop a customer support chatbot that answers FAQs in Marathi using this QA dataset",
            "Build an educational assistant that answers student questions about Marathi literature and history"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/marathi-squad')\nqa = ds['train'][0]\nprint(f\"Q: {qa['question']}\")\nprint(f\"A: {qa['answer_text']}\")\nprint(f\"Context: {qa['context'][:100]}...\")"
    },

    "l3cube-mahanews": {
        "schema": [
            {"field": "text", "type": "string", "description": "News headline in Marathi"},
            {"field": "label", "type": "string", "description": "News category (politics, sports, entertainment, etc.)"},
            {"field": "source", "type": "string", "description": "News source or publication"},
            {"field": "date", "type": "string", "description": "Publication date"}
        ],
        "starter_idea": "Build a news aggregation and classification system that categorizes Marathi news articles by topic",
        "build_ideas": [
            "Create a breaking news alert system that detects urgent news in Marathi and notifies users",
            "Develop a personalized news feed that recommends Marathi news based on user interests",
            "Build a fake news detector specifically trained on Marathi news articles"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/marathi-news')\nfor ex in ds['train'].take(5):\n    print(f\"[{ex['label']}] {ex['text']}\")"
    },

    "l3cube-mahaemotions": {
        "schema": [
            {"field": "text", "type": "string", "description": "Marathi text sample"},
            {"field": "emotion", "type": "string", "description": "Emotion label (happy, sad, angry, fearful, etc.)"},
            {"field": "intensity", "type": "float", "description": "Intensity of emotion (0-1)"},
            {"field": "context", "type": "string", "description": "Context category for the text"}
        ],
        "starter_idea": "Build an emotion detection service for Marathi mental health applications that identifies user emotional state",
        "build_ideas": [
            "Create a chatbot that responds empathetically based on detected emotional state of Marathi users",
            "Develop a content recommendation system that suggests uplifting content when negative emotions are detected",
            "Build an emotion analysis dashboard for tracking public sentiment during major events in Maharashtra"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('l3cube-pune/marathi-emotions')\nemotions_dist = {}\nfor ex in ds['train']:\n    emotions_dist[ex['emotion']] = emotions_dist.get(ex['emotion'], 0) + 1\nprint(f\"Emotion distribution: {emotions_dist}\")"
    },

    "ai4bharat-indiccorp-v2-mr": {
        "schema": [
            {"field": "text", "type": "string", "description": "Marathi text from the corpus"},
            {"field": "source", "type": "string", "description": "Source of the text (web, books, etc.)"},
            {"field": "language", "type": "string", "description": "Language identifier (mr)"},
            {"field": "length", "type": "int", "description": "Length of text in tokens"}
        ],
        "starter_idea": "Train a large Marathi language model using this corpus for downstream NLP tasks",
        "build_ideas": [
            "Fine-tune a GPT-style model on this data to create a Marathi text generation service",
            "Use this corpus to pre-train embeddings for Marathi semantic search applications",
            "Create a language model for code generation in Marathi educational platforms"
        ],
        "quick_start": "from datasets import load_dataset\nds = load_dataset('ai4bharat/indiccorp_v2', language='mr')\nfor ex in ds['train'].take(2):\n    print(f\"Text: {ex['text'][:100]}...\")\n    print(f\"Length: {len(ex['text'].split())} words\\n\")"
    }
}

def parse_catalog() -> List[Dict]:
    """Parse CATALOG.md."""
    catalog_path = Path(__file__).parent.parent / "CATALOG.md"
    datasets = []

    with open(catalog_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    in_table = False
    for line in lines:
        if line.startswith("|"):
            if not in_table and any(x in line for x in ["Category", "Dataset"]):
                in_table = True
                continue

            if in_table and line.strip() != "|" and "---" not in line:
                parts = [p.strip() for p in line.split("|")[1:-1]]
                if len(parts) >= 5 and not parts[0].startswith("--"):
                    try:
                        num, category, dataset, modality, license_str = parts[0], parts[1], parts[2], parts[3], parts[4]
                        if num and category and dataset:
                            slug = dataset.lower().replace(" ", "-").replace("(", "").replace(")", "").replace("_", "-")
                            datasets.append({
                                'title': dataset,
                                'slug': slug,
                                'category': category,
                                'modality': modality,
                                'license': license_str
                            })
                    except (IndexError, ValueError):
                        pass

    return datasets

def get_existing_yaml(dataset_slug: str) -> Dict[str, Any]:
    """Load existing YAML if it exists."""
    yaml_path = Path(__file__).parent.parent / "data_cards" / f"{dataset_slug}.yaml"
    if not yaml_path.exists():
        return {}
    try:
        with open(yaml_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f) or {}
    except Exception as e:
        print(f"Warning: Could not load {yaml_path}: {e}", file=sys.stderr)
        return {}

def save_yaml(dataset_slug: str, metadata: Dict[str, Any]) -> bool:
    """Save metadata to YAML."""
    yaml_path = Path(__file__).parent.parent / "data_cards" / f"{dataset_slug}.yaml"

    try:
        class CustomDumper(yaml.SafeDumper):
            pass

        def str_presenter(dumper, data):
            if '\n' in data:
                return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
            return dumper.represent_scalar('tag:yaml.org,2002:str', data)

        CustomDumper.add_representer(str, str_presenter)

        yaml_str = yaml.dump(metadata, Dumper=CustomDumper,
                            default_flow_style=False, allow_unicode=True, sort_keys=False)

        yaml_path.parent.mkdir(parents=True, exist_ok=True)
        with open(yaml_path, 'w', encoding='utf-8') as f:
            f.write("---\n")
            f.write(yaml_str)

        print(f"✓ {dataset_slug}")
        return True
    except Exception as e:
        print(f"✗ {dataset_slug}: {e}", file=sys.stderr)
        return False

def main():
    print("🚀 Generating Complete Metadata for Marathi Datasets\n")

    datasets = parse_catalog()
    print(f"Found {len(datasets)} datasets\n")

    processed = 0
    skipped = 0

    # Process datasets that have pre-generated metadata
    for dataset in datasets:
        if dataset['slug'] not in METADATA_LIBRARY:
            continue

        existing = get_existing_yaml(dataset['slug'])

        # Check if already has new fields
        if all(existing.get(k) for k in ['schema', 'starter_idea', 'build_ideas', 'quick_start']):
            skipped += 1
            continue

        # Merge
        metadata = {**existing, **METADATA_LIBRARY[dataset['slug']]}

        if save_yaml(dataset['slug'], metadata):
            processed += 1

    print(f"\n{'='*60}")
    print(f"Completed: {processed} generated, {skipped} already complete")
    print(f"{'='*60}\n")

    print("Note: This script demonstrates metadata generation with pre-generated content.")
    print("For full automation, use the complete_metadata.py script with ANTHROPIC_API_KEY")

if __name__ == "__main__":
    main()
